name       : python-ddt
version    : 1.2.1
release    : 3
source     :
    - https://files.pythonhosted.org/packages/6c/1e/6f33404c73f2ea97b9e44f6115cfc4a2e43b5d303cb288be427f8e194d72/ddt-1.2.1.tar.gz : d13e6af8f36238e89d00f4ebccf2bda4f6d1878be560a6600689e42077e164e3
license    : MIT
component  : programming.python
summary    : Data-Driven Tests for Python Unittest
description: |
    DDT (Data-Driven Tests) allows you to multiply one test case by running it with different test data, and make it appear as multiple test cases.
builddeps  :
    - python-mock
    - python-nose
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test
